# values.yaml

replicaCount: 2

image:
  repository: nardisync/mortgage_app
  tag: latest

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"

service:
  enabled: true
  type: LoadBalancer
  # annotations:
  #   key1: value1
  # loadBalancerIP: ""
  # externalTrafficPolicy: Cluster
  # nodePort: 30000
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
