# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mortgage-helm-chart.fullname" . }}
  labels:
    app: {{ include "mortgage-helm-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mortgage-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mortgage-helm-chart.name" . }}
    spec:
      containers:
        - name: mortgage-calculator-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.resources | indent 12 }}

      # Block of code for the service
      {{- if .Values.service.enabled }}
        ports:
          - containerPort: 8080
        {{- if eq .Values.service.type "LoadBalancer" }}
        {{- if .Values.service.annotations }}
        {{ toYaml .Values.service.annotations | indent 8 }}
        {{- end }}
        {{- if .Values.service.loadBalancerIP }}
        loadBalancerIP: {{ .Values.service.loadBalancerIP }}
        {{- end }}
        type: {{ .Values.service.type }}
        {{- if .Values.service.externalTrafficPolicy }}
        externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
        {{- end }}
        {{- else if eq .Values.service.type "NodePort" }}
        type: {{ .Values.service.type }}
        {{- if .Values.service.nodePort }}
        nodePort: {{ .Values.service.nodePort }}
        {{- end }}
        {{- end }}
        {{- if .Values.service.ports }}
        ports:
        {{- range $port := .Values.service.ports }}
          - name: {{ $port.name }}
            protocol: {{ $port.protocol }}
            port: {{ $port.port }}
            targetPort: {{ $port.targetPort }}
        {{- end }}
        {{- end }}
      {{- end }}



