# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mortgage-helm-chart.fullname" . }}-service
spec:
  selector:
    app: {{ include "mortgage-helm-chart.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
